name: Check Package

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies & build application
        run: make

      - name: Lint & format
        run: make lint

      - name: Run tests
        run: make test

      - name: Confirm no error
        run: make version
